server:
  port: 8082



spring:
  profiles:
    active: test
  servlet:
    multipart:
      enabled: true
      max-file-size: 50000MB
      max-request-size: 50000MB
  application:
    name: malaka-external
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.malaka.aat.external: DEBUG
    root: INFO

clients:
  malaka-internal:
    base-url: lb://malaka-internal
    service-account:
      username: external-service
      password: ExternalService@2024
  one-id:
    client-id: malaka_customs_uz
    client-secret: pC87xf6R82pHWD5hThIRF9fe
    redirect-uri: https://malaka.customs.uz/oauthOneID
    token:
      url: https://sso.egov.uz/sso/oauth/Authorization.do
      grant-type: one_authorization_code
    info:
      url: https://sso.egov.uz/sso/oauth/Authorization.do
      scope: malaka_customs_uz
      grant-type: one_access_token_identify
  egov:
    main-url: https://apimgw.egov.uz:8243
    mvd-request:
      address-path: /mvd/services/address/info/pin/v1
    gcp-request:
      path: /gcp/docrest/v1
      lang-id: 1
      transaction-id: 3
      is_consent: Y
      is_photo: Y
      sender: M
    token:
      url: https://iskm.egov.uz:9444
      token-path: /oauth2/token
      grant-type: password
      username: gtk-user
      password: ZRIoHbHl9KEqbyird3oa
      basic-auth:
        username: hxeP_G0DgeZ38M7Wr60FlVPtWQYa
        password: DGOfftPG8Ba60LYFum2d4h9hx6ca
