spring:
  datasource:
    url: jdbc:h2:file:./data-external/mydb;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://192.168.214.222:8761/eureka/

app:
  projectUrl: http://192.168.214.222:8585
  file:
    path: /var/lib/malaka-external/files/
    user-images:
      path: /var/lib/malaka-external/files/
  security:
    secretKey: Y1ZNbXM1aGZTaWlxbnowMWc3UTFuSTgxZEp5eFdKdjE=
    accessTokenExpirationInHours: 1
    refreshTokenExpirationInHours: 24
