spring:
  datasource:
    url: jdbc:h2:file:./data-external/mydb;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  projectUrl: http://localhost:8585
  file:
    path: C:/Users/irism/Desktop/MalakaFiles/external/images/
  security:
    secretKey: Y1ZNbXM1aGZTaWlxbnowMWc3UTFuSTgxZEp5eFdKdjE=
    accessTokenExpirationInHours: 1
    refreshTokenExpirationInHours: 24

clients:
  malaka-internal:
    base-url: lb://malaka-internal