spring:
  datasource:
    url: jdbc:as400://172.16.111.1/BIMALAKA_EXT;naming=system;translate binary=true;package cache=true;lob threshold=1048576
    username: UJAXON01
    password: JaX0n1002
    driver-class-name: com.ibm.as400.access.AS400JDBCDriver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2400Dialect

eureka:
  client:
    service-url:
      defaultZone: http://192.168.214.222:8761/eureka/

app:
  projectUrl: http://192.168.214.222:8585
  file:
    path: /var/lib/malaka-external/files/
    user-images:
      path: /var/lib/malaka-external/files/
  security:
    secretKey: Y1ZNbXM1aGZTaWlxbnowMWc3UTFuSTgxZEp5eFdKdjE=
    accessTokenExpirationInHours: 1
    refreshTokenExpirationInHours: 24

clients:
  malaka-internal:
    base-url: http://192.168.214.222:8081/api/auth/login