spring:
  datasource:
    url: jdbc:as400://172.16.111.1/BIMALAKA_EXT;naming=system;translate binary=true;package cache=true;lob threshold=1048576
    username: UJAXON01
    password: JaX0n1002
    driver-class-name: com.ibm.as400.access.AS400JDBCDriver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2400Dialect

app:
  projectUrl: http://192.168.25.4:8585
  file:
    path: C:/Users/j.irismatov/Desktop/MalakaFiles/external/images/
  security:
    secretKey: Y1ZNbXM1aGZTaWlxbnowMWc3UTFuSTgxZEp5eFdKdjE=
    accessTokenExpirationInHours: 1
    refreshTokenExpirationInHours: 24