spring:
  datasource:
    url: jdbc:h2:file:./data-internal/mydb;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  security:
    secretKey: Y1ZNbXM1aGZTaWlxbnowMWc3UTFuSTgxZEp5eFdKdjE=
    accessTokenExpirationInHours: 1
    refreshTokenExpirationInHours: 24
  file:
    path: C:/Users/irism/Desktop/MalakaFiles/internal/images/
    video-path: C:/Users/irism/Desktop/MalakaFiles/internal/videos/
    chunk-size: 5242880