spring:
  datasource:
    url: jdbc:as400://172.16.111.1/BIMALAKA;
    username: UJAXON01
    password: JaX0n1002
    driver-class-name: com.ibm.as400.access.AS400JDBCDriver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2400Dialect

app:
  security:
    secretKey: Y1ZNbXM1aGZTaWlxbnowMWc3UTFuSTgxZEp5eFdKdjE=
    accessTokenExpirationInHours: 1
    refreshTokenExpirationInHours: 24
  file:
    path: C:/Users/j.irismatov/Desktop/MalakaFiles/internal/images/
    video-path: C:/Users/j.irismatov/Desktop/MalakaFiles/internal/videos/
    chunk-size: 5242880