server:
  port: 8081

spring:
  application:
    name: malaka-internal
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 50000MB
      max-request-size: 50000MB





# Client Configuration for External Services
clients:
  malaka-external:
    base-url: lb://malaka-external
    service-account:
      username: internal-service
      password: InternalService@2025
  egov:
    main-url: https://apimgw.egov.uz:8243
    mvd-request:
      address-path: /mvd/services/address/info/pin/v1
    gcp-request:
      path: /gcp/docrest/v1
      lang-id: 1
      transaction-id: 3
      is_consent: Y
      is_photo: N
      sender: M
    token:
      url: https://iskm.egov.uz:9444
      token-path: /oauth2/token
      grant-type: password
      username: gtk-user
      password: ZRIoHbHl9KEqbyird3oa
      basic-auth:
        username: hxeP_G0DgeZ38M7Wr60FlVPtWQYa
        password: DGOfftPG8Ba60LYFum2d4h9hx6ca

# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always