spring:
  datasource:
    url: jdbc:as400://172.16.111.1/BIMALAKA;libraries=BIMALAKA;naming=system;translate binary=true;package cache=true;lob threshold=1048576
    username: UJAXON01
    password: JaX0n1002
    driver-class-name: com.ibm.as400.access.AS400JDBCDriver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DB2400Dialect